const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    CHANGE_LANGUAGES: 'CHANGE_LANGUAGES',

    //admin
    FETCH_GENDER_START: 'FETCH_GENDER_START',
    FETCH_GENDER_SUCCESS: 'FETCH_GENDER_SUCCESS',
    FETCH_GENDER_FAILED: 'FETCH_GENDER_FAILED',
    
    FETCH_POSITION_START: 'FETCH_POSITION_START',
    FETCH_POSITION_SUCCESS: 'FETCH_POSITION_SUCCESS',
    FETCH_POSITION_FAILED: 'FETCH_POSITION_FAILED',

    FETCH_ROLE_START: 'FETCH_ROLE_START',
    FETCH_ROLE_SUCCESS: 'FETCH_ROLE_SUCCESS',
    FETCH_ROLE_FAILED: 'FETCH_ROLE_FAILED',

    FETCH_DOCTOR_PRICE_START: 'FETCH_DOCTOR_PRICE_START',
    FETCH_DOCTOR_PRICE_SUCCESS: 'FETCH_DOCTOR_PRICE_SUCCESS',
    FETCH_DOCTOR_PRICE_FAILED: 'FETCH_DOCTOR_PRICE_FAILED',

    FETCH_PAYMENT_START: 'FETCH_PAYMENT_START',
    FETCH_PAYMENT_SUCCESS: 'FETCH_PAYMENT_SUCCESS',
    FETCH_PAYMENT_FAILED: 'FETCH_PAYMENT_FAILED',

    FETCH_PROVINCE_START: 'FETCH_PROVINCE_START',
    FETCH_PROVINCE_SUCCESS: 'FETCH_PROVINCE_SUCCESS',
    FETCH_PROVINCE_FAILED: 'FETCH_PROVINCE_FAILED',

    FETCH_SPECIALTY_START: 'FETCH_SPECIALTY_START',
    FETCH_SPECIALTY_SUCCESS: 'FETCH_SPECIALTY_SUCCESS',
    FETCH_SPECIALTY_FAILED: 'FETCH_SPECIALTY_FAILED',

    FETCH_CLINIC_START: 'FETCH_CLINIC_START',
    FETCH_CLINIC_SUCCESS: 'FETCH_CLINIC_SUCCESS',
    FETCH_CLINIC_FAILED: 'FETCH_CLINIC_FAILED',
    



    CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
    CREATE_USER_FAILED: 'CREATE_USER_FAILED',

    FETCH_ALL_USERS_SUCCESS: 'FETCH_ALL_USERS_SUCCESS',
    FETCH_ALL_USERS_FAILED: 'FETCH_ALL_USERS_FAILED',

    DELETE_USERS_SUCCESS: 'DELETE_USERS_SUCCESS',
    DELETE_USERS_FAILED: 'DELETE_USERS_FAILED',

    EDIT_USERS_SUCCESS: 'EDIT_USERS_SUCCESS',
    EDIT_USERS_FAILED: 'EDIT_USERS_FAILED',


    FETCH_TOP_DOCTOR_SUCCESS: 'FETCH_TOP_DOCTOR_SUCCESS',
    FETCH_TOP_DOCTOR_FAILED: 'FETCH_TOP_DOCTOR_FAILED',


    FETCH_ALL_DOCTOR_SUCCESS: 'FETCH_ALL_DOCTOR_SUCCESS',
    FETCH_ALL_DOCTOR_FAILED: 'FETCH_ALL_DOCTOR_FAILED',


    SAVE_DETAIL_DOCTOR_SUCCESS: 'SAVE_DETAIL_DOCTOR_SUCCESS',
    SAVE_DETAIL_DOCTOR_FAILED: 'SAVE_DETAIL_DOCTOR_FAILED',

    FETCH_ALLCODE_SCHEDULE_TIME_SUCCESS: 'FETCH_ALLCODE_SCHEDULE_TIME_SUCCESS',
    FETCH_ALLCODE_SCHEDULE_TIME_FAILED: 'FETCH_ALLCODE_SCHEDULE_TIME_FAILED',

    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    USER_LOGIN_SUCCESS:'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',
})

export default actionTypes;